#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
# add any opscode dependencey you may have by adding a line like the following:
# cookbooks 'cookbook_name'
## and optionally 
# cookbooks 'cookbook_name', 'cookbook-version' # e.g '1.0.0'
#cookbook 'java', :git => 'git@github.com:opscode-cookbooks/java.git', :ref => 'master'
#cookbook 'sudo'
cookbook 'windows', '1.9.0' #(see: COOK-4142)
#cookbook 'powershell', '1.1.2'
cookbook 'java'
#cookbook 'redmine', :git => 'git@github.com:tikalk-cookbooks/redmine.git'
cookbook 'redmine', :git => 'https://github.com/juanje/cookbook-redmine.git', :ref => '0.1.0'
#cookbook 'gitlab', :git => 'git@github.com:tikalk-cookbooks/gitlab.git'
cookbook 'alm', :path => 'chef/site-cookbooks/alm'
#cookbook 'jenkins', git => 'git@github.com:tikalk-cookbooks/jenkins.git'
#cookbook 'nexus', git => 'git@github.com:tikalk-cookbooks/nexus.git'
cookbook 'jenkins', :git => 'https://github.com/opscode-cookbooks/jenkins.git', :ref => 'v1.1.0'
cookbook 'chef-user', :git => 'https://github.com/fnichol/chef-user.git', :ref => 'v0.3.0'
cookbook 'chef-solo-search', :git => 'https://github.com/edelight/chef-solo-search.git', :ref => '0.5.1'
cookbook 'iptables', :git => 'https://github.com/opscode-cookbooks/iptables.git', :ref => '0.12.0'
cookbook 'tikal-jenkins', :git => 'https://github.com/tikalk-cookbooks/tikal-jenkins.git', :ref => 'master'
